# Production Configuration (Cloud)

# Database Connection (Injected via Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Server Port (Standard for Cloud Containers)
server.port=8080

# Security (JWT)
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000 
# 1 day expiration for prod
